// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NETCore.Ldap.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BindRequestFeature : Xunit.IClassFixture<BindRequestFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BindRequest.feature"
#line hidden
        
        public BindRequestFeature(BindRequestFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BindRequest", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Login and password authentication")]
        [Xunit.TraitAttribute("FeatureTitle", "BindRequest")]
        [Xunit.TraitAttribute("Description", "Login and password authentication")]
        public virtual void LoginAndPasswordAuthentication()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login and password authentication", null, ((string[])(null)));
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table1.AddRow(new string[] {
                        "objectClass",
                        "inetOrgPerson"});
            table1.AddRow(new string[] {
                        "objectClass",
                        "organizationalPerson"});
            table1.AddRow(new string[] {
                        "objectClass",
                        "person"});
            table1.AddRow(new string[] {
                        "objectClass",
                        "top"});
            table1.AddRow(new string[] {
                        "cn",
                        "administrator"});
            table1.AddRow(new string[] {
                        "sn",
                        "administrator"});
            table1.AddRow(new string[] {
                        "uid",
                        "administrator"});
            table1.AddRow(new string[] {
                        "userPassword",
                        "password"});
#line 4
 testRunner.Given("Add LDAP entry \'uid=administrator,ou=users,ou=system\'", ((string)(null)), table1, "Given ");
#line 15
 testRunner.When("Authenticate user with login \'uid=administrator,ou=users,ou=system\', password \'pa" +
                    "ssword\' and MessageId \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("LDAP Packet \'MessageId.Value\'=\'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.Then("LDAP Packet \'ProtocolOperation.Operation.Result.ResultCode.Value\'=\'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
 testRunner.Then("LDAP Packet \'ProtocolOperation.Operation.Result.MatchedDN.Value\'=\'uid=administrat" +
                    "or,ou=users,ou=system\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                BindRequestFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                BindRequestFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
