// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NETCore.Ldap.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SearchRequestErrorFeature : Xunit.IClassFixture<SearchRequestErrorFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SearchRequestError.feature"
#line hidden
        
        public SearchRequestErrorFeature(SearchRequestErrorFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SearchRequestError", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Search request and base object does not exist")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchRequestError")]
        [Xunit.TraitAttribute("Description", "Search request and base object does not exist")]
        public virtual void SearchRequestAndBaseObjectDoesNotExist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search request and base object does not exist", null, ((string[])(null)));
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table23.AddRow(new string[] {
                        "objectClass",
                        "inetOrgPerson"});
            table23.AddRow(new string[] {
                        "objectClass",
                        "organizationalPerson"});
            table23.AddRow(new string[] {
                        "objectClass",
                        "person"});
            table23.AddRow(new string[] {
                        "objectClass",
                        "top"});
            table23.AddRow(new string[] {
                        "cn",
                        "administrator"});
            table23.AddRow(new string[] {
                        "sn",
                        "administrator"});
            table23.AddRow(new string[] {
                        "uid",
                        "administrator"});
            table23.AddRow(new string[] {
                        "userPassword",
                        "password"});
#line 4
 testRunner.Given("Add LDAP entry \'admin11\'", ((string)(null)), table23, "Given ");
#line 15
 testRunner.When("Authenticate user with login \'admin11\', password \'password\' and MessageId \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.And("Search LDAP entries, base object is \'invalid\', message identifier is \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.Then("extract JSON \'searchResultDone\', JSON \'MessageId.Value\'=\'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
 testRunner.Then("extract JSON \'searchResultDone\', JSON \'ProtocolOperation.Operation.Result.ResultC" +
                    "ode.Value\'=\'32\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.Then("extract JSON \'searchResultDone\', JSON \'ProtocolOperation.Operation.Result.Diagnos" +
                    "ticMessage.Value\'=\'entry \'invalid\' doesn\'t exist\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SearchRequestErrorFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SearchRequestErrorFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
